FROM python:3.8.2-slim-buster


COPY ./requirements_websocket.txt ./
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements_websocket.txt

COPY ./user_data/. ./user_data/

WORKDIR /Binance_volatility_trading_bot_main
COPY ./Binance_volatility_trading_bot_main/. ./Binance_volatility_trading_bot_main/

#EXPOSE 5432

ENV PYTHONPATH=/Binance_volatility_trading_bot_main

#CMD python ed_binance_websocket_service.py
CMD ["python","-u","ed_binance_websocket_service.py"]